name: pickndeliver
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  shared_preferences: ^0.5.2
  http: ^0.12.0+2
  flutter_datetime_picker: ^1.3.5
  fluttertoast: ^3.1.3
  image_picker: ^0.6.5
  url_launcher: any
  multiselect_formfield: ^0.1.2
  dio: ^3.0.9
  progress_dialog: ^1.2.0
  flutter_native_image: ^0.0.5
  google_maps_flutter: ^0.5.26
  location: ^2.3.5
  geolocator: ^5.2.0
  flutter_google_places: ^0.2.4
  geocoder: ^0.2.1
  firebase_messaging: ^6.0.9
  flutter_local_notifications: ^1.4.2
  share: ^0.6.4+2
  path_provider: ^1.6.8
  animated_text_kit: ^2.0.0
  cloud_firestore: ^0.14.1+3
  #bcoz outadeted -  kd
  #permission_handler: ^4.3.0
  contacts_service: ^0.3.10
  carousel_slider: ^2.1.0
  shimmer: ^1.1.1
  webview_flutter: ^0.3.22+1
  firebase_core: ^0.5.0+1
  firebase_auth: 0.18.1+2
  pin_input_text_field: ^3.0.2
  simple_animations: ^2.2.1
  razorpay_flutter: ^1.2.2
  # flutter_launch: ^0.2.0
  carousel_pro: ^1.0.0
  #  added new feature -kd
  flutter_open_whatsapp: ^0.1.2
  permission_handler: ^5.0.1+1
  flushbar: 1.10.4
  vibration: 1.4.0
  autocomplete_textfield: 1.7.3
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
